name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Desplegar función de Cloud Storage Trigger
      - name: Deploy Cloud Function (Storage Trigger)
        run: |
          gcloud functions deploy process_file \
            --runtime python310 \
            --trigger-resource ${{ secrets.GCP_BUCKET_NAME }} \
            --trigger-event google.storage.object.finalize \
            --entry-point process_file \
            --region us-central1 \
            --allow-unauthenticated

      # Verificar que la función Storage Trigger existe
      - name: Verificar función Storage Trigger
        run: gcloud functions describe process_file --region us-central1

      # Desplegar función HTTP Trigger
      - name: Deploy Cloud Function (HTTP Trigger)
        run: |
          gcloud functions deploy http_hello_world \
            --runtime python310 \
            --trigger-http \
            --entry-point http_hello_world \
            --region us-central1 \
            --allow-unauthenticated

      # Verificar que la función HTTP Trigger existe
      - name: Verificar función HTTP Trigger
        run: gcloud functions describe http_hello_world --region us-central1

      # Obtener y mostrar la URL de la función HTTP (corregido)
      - name: Obtener URL de función HTTP
        run: |
          FUNCTION_URL=$(gcloud functions describe http_hello_world --region us-central1 --format='value(serviceConfig.uri)')
          echo "URL: $FUNCTION_URL"

      # Probar la función HTTP con una solicitud POST
      - name: Probar función HTTP
        run: |
          FUNCTION_URL=$(gcloud functions describe http_hello_world --region us-central1 --format='value(serviceConfig.uri)')
          curl -X POST "$FUNCTION_URL" -H "Content-Type: application/json" -d '{"name": "GitHub Actions"}'

      # Subir archivo de prueba a Cloud Storage para activar la función process_file
      - name: Subir archivo de prueba a Cloud Storage
        run: |
          echo "Test file" > test.txt
          gsutil cp test.txt gs://${{ secrets.GCP_BUCKET_NAME }}/test.txt

      # Obtener logs recientes de la función HTTP
      - name: Obtener logs de función HTTP
        run: gcloud functions logs read http_hello_world --region us-central1 --limit 10

      # Obtener logs recientes de la función Storage Trigger
      - name: Obtener logs de función Storage Trigger
        run: gcloud functions logs read process_file --region us-central1 --limit 10
